name: Bug report
description: 回報錯誤或異常
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    id: repro
    attributes:
      label: 重現步驟
      description: 請詳述操作步驟與環境
      placeholder: "1) ...\n2) ..."
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: 日誌/截圖
      description: 附上錯誤訊息、堆疊或截圖
